### ISSUE TITLE
Make sidenav stay visible on scroll

### ISSUE THREAD

**Issue by jordangov** [Code-dot-mil/code.mil#138]
The navigation on ‘How to Open Source’  and ‘FAQ’ (or really on any page with side-nav) should have the side-nav scroll with the user down the page, not stay locked at the top.

**Comment by arichiv-usds** [comment]
I should fix this in the library using https://github.com/18F/uswds-jekyll/issues/100

**Comment by jordangov** [comment]
Oooh... even better

**Comment by line47** [comment]
We'd love your participation @arichiv-usds 🎉
