### ISSUE TITLE
Move this repo to code-dot-mil organization

### ISSUE THREAD

**Issue by arichiv-usds** [Code-dot-mil/code.mil#172]
- [x] Setup Travis CI for `code-dot-mil`
- [x] Transfer `deptofdefense/code.mil` -> `code-dot-mil/code.mil`
- [x] Create a new `deptofdefense/code.mil` that pushes people to `code-dot-mil/code.mil`
- [ ] Fix links in medium post

**Comment by arichiv-usds** [comment]
@jordangov Let me know when to proceed :-)

**Comment by arichiv-usds** [comment]
See https://github.com/deptofdefense/redirect.code.mil for what I was thinking of for a redirection repo

**Comment by arichiv-usds** [comment]
@shawoods and @reinastaley for review

**Comment by jordangov** [comment]
I'm good with this move generally, but I wanted to get Sharon's take on it first just in case there's any legal weirdness.

**Comment by arichiv-usds** [comment]
@bowtietim Sound good?

**Comment by jordangov** [comment]
Tim's great, but we need @shawoods to sign off.

**Comment by arichiv-usds** [comment]
Sorry, @shawoods said she was good as long as @bowtietim signed off

**Comment by jordangov** [comment]
Aaah... gotcha! Cool beans.

**Comment by timvanname** [comment]
I’m good with this. Thank you both!

**Comment by davidbgk** [comment]
There are still a lot of references/links to the previous repository, see https://github.com/Code-dot-mil/code.mil/search?utf8=%E2%9C%93&q=deptofdefense&type=

**Comment by arichiv-usds** [comment]
That's a great catch! I'll fix the links, @jordangov can you get the medium post?

**Comment by jordangov** [comment]
I don't control that... maybe @jgarber623-gov ?
