### ISSUE TITLE
Add "help wanted" labels to this repo and some issues

### ISSUE THREAD

**Issue by jordangov** [Code-dot-mil/code.mil#175]
The [documentation](https://github.com/GSA/code-gov/blob/master/HelpWanted.md) for how to do that is on the Code.gov GitHub repo.

**Comment by arichiv-usds** [comment]
I tagged a couple, is the next task to expose them on code.mil the way code.gov does?

**Comment by jordangov** [comment]
Nope, they'll get picked up by Code.gov. But we need to implement the other labels to get them categorized on the Code.gov site. That includes the level of effort and such.

**Comment by jordangov** [comment]
Done!
