### ISSUE TITLE
Add favicon to the website

### ISSUE THREAD

**Issue by BalajiJBcs** [Code-dot-mil/code.mil#201]
The favicon for the code.mil is the US flag, but right now there is no mechanism to show favicon at code.mil
adding the following snippet to header would  fix the problem

`<link rel="shortcut icon" type="image/x-icon" href="https://www.code.mil/assets/uswds/img/favicons/favicon-57.png"/>`
or 

`<link rel="shortcut icon" type="image/x-icon" href="assets/uswds/img/favicons/favicon-57.png" /> `

**Comment by arichiv** [comment]
Merging with #147
