### ISSUE TITLE
Missing content on home page 

### ISSUE THREAD

**Issue by arichiv** [Code-dot-mil/code.mil#213]
@jordangov

**Comment by jordangov** [comment]
:) Thanks... maybe a bit more in here? 😛 

Need to figure out why the automated screenshot grabber isn't capturing the entire page.

**Comment by arichiv** [comment]
@jordangov looks like the whole page to me: https://www.code.mil/

**Comment by jordangov** [comment]
So ... I think it's bigger than just the Press section. We're missing the ["What is Code.mil"](https://github.com/Code-dot-mil/code.mil/blob/master/_pages/index.md) bit as well.

**Comment by arichiv** [comment]
I'm guessing it's a uswds library change

**Comment by arichiv** [comment]
this is the kind of change screenshots will help catch :-)
