### ISSUE TITLE
Add DDS.mil website to inventory

### ISSUE THREAD

**Issue by jordangov** [Code-dot-mil/code.mil#245]
## Feature

I would like to add the [DDS.mil website/repo](https://github.com/deptofdefense/dds.mil) to the code.json inventory file for DoD/Code.mil.

## Page(s) Affected

https://code.mil/code.json

**Comment by milovanderlinden** [comment]
Am I correct that this one can be closed now?

**Comment by jordangov** [comment]
Yep! Thanks.
